import { createHash, createHmac, randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';
import { createReadStream, existsSync, mkdirSync } from 'node:fs';
import { stat } from 'node:fs/promises';
import { createServer } from 'node:http';
import { request as httpsRequest } from 'node:https';
import { dirname, extname, join, normalize, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { DatabaseSync } from 'node:sqlite';

const root = dirname(fileURLToPath(import.meta.url));
const env = globalThis.process?.env ?? {};
const port = Number(env.PORT || 3000);
const appUrl = env.APP_URL || `http://localhost:${port}`;
const isProduction = env.NODE_ENV === 'production';
const sessionSecret = env.LEDGERLANE_SESSION_SECRET || 'development-only-change-this-before-production';
const allowDemo = env.ALLOW_DEMO === 'true' || !isProduction;
if (isProduction && sessionSecret.length < 32) throw new Error('LEDGERLANE_SESSION_SECRET must be at least 32 characters in production.');

const dataDirectory = env.LEDGERLANE_DATA_DIR || join(root, 'data');
if (!existsSync(dataDirectory)) mkdirSync(dataDirectory, { recursive: true });
const db = new DatabaseSync(join(dataDirectory, 'ledgerlane.db'));
db.exec(`
  PRAGMA journal_mode = WAL;
  PRAGMA foreign_keys = ON;
  PRAGMA busy_timeout = 5000;
  CREATE TABLE IF NOT EXISTS organizations (id TEXT PRIMARY KEY, name TEXT NOT NULL, plan TEXT NOT NULL DEFAULT 'starter', created_at TEXT NOT NULL);
  CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, org_id TEXT NOT NULL REFERENCES organizations(id), email TEXT NOT NULL UNIQUE, name TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('owner','admin','controller','accountant','auditor')), password_salt TEXT NOT NULL, password_hash TEXT NOT NULL, created_at TEXT NOT NULL);
  CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), token_hash TEXT NOT NULL UNIQUE, expires_at TEXT NOT NULL, created_at TEXT NOT NULL);
  CREATE TABLE IF NOT EXISTS workflows (id TEXT PRIMARY KEY, org_id TEXT NOT NULL REFERENCES organizations(id), type TEXT NOT NULL, title TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('draft','active','review','complete')), progress INTEGER NOT NULL DEFAULT 0 CHECK(progress BETWEEN 0 AND 100), owner_id TEXT REFERENCES users(id), due_date TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
  CREATE TABLE IF NOT EXISTS exceptions (id TEXT PRIMARY KEY, org_id TEXT NOT NULL REFERENCES organizations(id), title TEXT NOT NULL, description TEXT NOT NULL, amount_cents INTEGER NOT NULL DEFAULT 0, severity TEXT NOT NULL CHECK(severity IN ('material','review','control')), status TEXT NOT NULL CHECK(status IN ('open','resolved')), assignee_id TEXT REFERENCES users(id), created_at TEXT NOT NULL, resolved_at TEXT);
  CREATE TABLE IF NOT EXISTS audit_events (id TEXT PRIMARY KEY, org_id TEXT NOT NULL REFERENCES organizations(id), actor_id TEXT REFERENCES users(id), action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
  CREATE TABLE IF NOT EXISTS subscriptions (org_id TEXT PRIMARY KEY REFERENCES organizations(id), provider_customer_id TEXT, provider_subscription_id TEXT, plan TEXT NOT NULL DEFAULT 'starter', status TEXT NOT NULL DEFAULT 'active', updated_at TEXT NOT NULL);
  CREATE TABLE IF NOT EXISTS leads (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, name TEXT NOT NULL, company TEXT NOT NULL, team_size TEXT NOT NULL, notes TEXT NOT NULL DEFAULT '', source TEXT NOT NULL, created_at TEXT NOT NULL);
  CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token_hash);
  CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON sessions(expires_at);
  CREATE INDEX IF NOT EXISTS idx_workflows_org ON workflows(org_id, updated_at DESC);
  CREATE INDEX IF NOT EXISTS idx_exceptions_org_status ON exceptions(org_id, status, created_at DESC);
  CREATE INDEX IF NOT EXISTS idx_audit_org_created ON audit_events(org_id, created_at DESC);
`);

const id = () => randomBytes(16).toString('hex');
const now = () => new Date().toISOString();
const one = (sql, ...params) => db.prepare(sql).get(...params);
const all = (sql, ...params) => db.prepare(sql).all(...params);
const run = (sql, ...params) => db.prepare(sql).run(...params);
const hashToken = token => createHash('sha256').update(`${sessionSecret}:${token}`).digest('hex');
const hashPassword = (password, salt = randomBytes(16).toString('hex')) => ({ salt, hash: scryptSync(password, salt, 64).toString('hex') });
const verifyPassword = (password, salt, expected) => timingSafeEqual(Buffer.from(scryptSync(password, salt, 64).toString('hex'), 'hex'), Buffer.from(expected, 'hex'));
const money = cents => `$${(cents / 100).toLocaleString('en-US', { maximumFractionDigits: 0 })}`;
const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const roleCanWrite = ['owner', 'admin', 'controller', 'accountant'];
const securityHeaders = {
  'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=()', 'Cross-Origin-Opener-Policy': 'same-origin',
  'Content-Security-Policy': "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; font-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'",
  ...(isProduction ? { 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains' } : {})
};

function record(orgId, actorId, action, entityType, entityId, metadata = {}) { run('INSERT INTO audit_events VALUES (?, ?, ?, ?, ?, ?, ?, ?)', id(), orgId, actorId, action, entityType, entityId, JSON.stringify(metadata), now()); }
function seedDemo() {
  const email = 'leila@atlas.example'; let user = one('SELECT id, org_id FROM users WHERE email=?', email); const timestamp = now();
  if (!user) { const orgId = id(), userId = id(), credential = hashPassword('Atlas!2026'); run('INSERT INTO organizations VALUES (?, ?, ?, ?)', orgId, 'Atlas Holdings', 'growth', timestamp); run('INSERT INTO users VALUES (?, ?, ?, ?, ?, ?, ?, ?)', userId, orgId, email, 'Leila Morgan', 'controller', credential.salt, credential.hash, timestamp); user = { id: userId, org_id: orgId }; }
  const orgId = user.org_id, userId = user.id;
  if (!one('SELECT org_id FROM subscriptions WHERE org_id=?', orgId)) run('INSERT INTO subscriptions VALUES (?, NULL, NULL, ?, ?, ?)', orgId, 'growth', 'active', timestamp);
  if (!one('SELECT id FROM workflows WHERE org_id=? LIMIT 1', orgId)) for (const [type, title, status, progress, dueDate] of [['reconciliation','Bank reconciliation','active',85,'2026-10-27'],['accrual','Revenue accrual review','review',67,'2026-10-26'],['evidence','Vendor control evidence','active',58,'2026-10-28']]) run('INSERT INTO workflows VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', id(), orgId, type, title, status, progress, userId, dueDate, timestamp, timestamp);
  if (!one('SELECT id FROM exceptions WHERE org_id=? LIMIT 1', orgId)) for (const [title, description, amount, severity] of [['Resolve AP variance','AI found an unexplained 18.4% increase in office expense',4820000,'material'],['Approve revenue accrual','Forecast confidence is 97% · $124,000 proposed',12400000,'review'],['Request missing evidence','3 vendor confirmations are due before control sign-off',0,'control']]) run('INSERT INTO exceptions VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, NULL)', id(), orgId, title, description, amount, severity, 'open', userId, timestamp);
  if (!one('SELECT id FROM audit_events WHERE org_id=? LIMIT 1', orgId)) { record(orgId, userId, 'completed', 'workflow', 'payroll', { title: 'Payroll reconciliation completed', detail: 'Matched against Gusto · Evidence packaged' }); record(orgId, userId, 'drafted', 'journal_entry', 'accruals', { title: 'Lane drafted 4 accrual entries', detail: 'Based on contract terms and prior periods' }); record(orgId, userId, 'approved', 'control', 'FIN-102', { title: 'Leila approved “Bank reconciliation”', detail: 'Control FIN-102 · Approval recorded' }); }
}
if (allowDemo) seedDemo();

function parseCookies(header = '') { return Object.fromEntries(header.split(';').map(value => value.trim().split('=').map(decodeURIComponent)).filter(([key, value]) => key && value)); }
function setSession(res, userId) { const token = randomBytes(32).toString('base64url'), expiry = new Date(Date.now() + 1000 * 60 * 60 * 24 * 14).toISOString(); run('INSERT INTO sessions VALUES (?, ?, ?, ?, ?)', id(), userId, hashToken(token), expiry, now()); res.setHeader('Set-Cookie', `ledgerlane_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=1209600${isProduction ? '; Secure' : ''}`); }
function clearSession(res) { res.setHeader('Set-Cookie', `ledgerlane_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0${isProduction ? '; Secure' : ''}`); }
function actor(req) { const token = parseCookies(req.headers.cookie).ledgerlane_session; if (!token) return null; return one(`SELECT u.id, u.org_id, u.email, u.name, u.role, o.name organization, o.plan FROM sessions s JOIN users u ON u.id=s.user_id JOIN organizations o ON o.id=u.org_id WHERE s.token_hash=? AND s.expires_at>?`, hashToken(token), now()); }
function cleanText(value, max) { return typeof value === 'string' ? value.trim().replace(/\s+/g, ' ').slice(0, max) : ''; }
async function readBody(req, limit = 1_000_000) { let data = ''; for await (const chunk of req) { data += chunk; if (data.length > limit) throw Object.assign(new Error('Request body is too large'), { status: 413 }); } return data; }
async function jsonBody(req) { const data = await readBody(req); try { return data ? JSON.parse(data) : {}; } catch { throw Object.assign(new Error('Invalid JSON body'), { status: 400 }); } }
function json(res, status, payload) { res.writeHead(status, { ...securityHeaders, 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' }); res.end(JSON.stringify(payload)); }
function error(res, status, message) { json(res, status, { error: message }); }
function requireActor(req, res, allowedRoles) { const user = actor(req); if (!user) { error(res, 401, 'Sign in required'); return null; } if (allowedRoles && !allowedRoles.includes(user.role)) { error(res, 403, 'Your role does not have permission for this action'); return null; } return user; }
function assertSameOrigin(req, res) { if (!['POST', 'PATCH', 'PUT', 'DELETE'].includes(req.method)) return true; const origin = req.headers.origin; if (origin && origin !== appUrl) { error(res, 403, 'Cross-site requests are not permitted'); return false; } return true; }
function dashboard(user) { const exceptions = all(`SELECT e.*, u.name assignee FROM exceptions e LEFT JOIN users u ON u.id=e.assignee_id WHERE e.org_id=? AND e.status='open' ORDER BY CASE e.severity WHEN 'material' THEN 1 WHEN 'review' THEN 2 ELSE 3 END, e.created_at`, user.org_id); const workflows = all('SELECT * FROM workflows WHERE org_id=? ORDER BY updated_at DESC', user.org_id); const activity = all(`SELECT a.*, u.name actor_name FROM audit_events a LEFT JOIN users u ON u.id=a.actor_id WHERE a.org_id=? ORDER BY a.created_at DESC LIMIT 8`, user.org_id); const total = exceptions.reduce((sum, item) => sum + item.amount_cents, 0); const progress = workflows.length ? Math.round(workflows.reduce((sum, item) => sum + item.progress, 0) / workflows.length) : 0; return { user, metrics: { closeHealth: Math.min(100, 72 + Math.round(progress * .25)), automatedHours: 186, exceptionAmount: money(total), exceptionCount: exceptions.length, evidenceCoverage: 98.6, closeProgress: progress }, exceptions, workflows, activity }; }
function externalJson(url, headers, payload) { return new Promise((resolve, reject) => { const content = JSON.stringify(payload), request = httpsRequest(url, { method: 'POST', headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(content), ...headers }, timeout: 15_000 }, response => { let data = ''; response.on('data', chunk => data += chunk); response.on('end', () => { try { const parsed = JSON.parse(data); if (response.statusCode < 200 || response.statusCode >= 300) reject(new Error(parsed.error?.message || parsed.errors?.[0]?.detail || 'External API request failed')); else resolve(parsed); } catch { reject(new Error('Invalid response from external API')); } }); }); request.on('timeout', () => request.destroy(new Error('External API request timed out'))); request.on('error', reject); request.end(content); }); }
async function lemonCheckout(plan, user) { const variant = plan === 'scale' ? env.LEMONSQUEEZY_VARIANT_SCALE : env.LEMONSQUEEZY_VARIANT_GROWTH; if (!env.LEMONSQUEEZY_API_KEY || !env.LEMONSQUEEZY_STORE_ID || !variant) return null; const payload = { data: { type: 'checkouts', attributes: { checkout_data: { email: user.email, custom: { org_id: user.org_id, plan } }, product_options: { redirect_url: `${appUrl}/app?billing=success`, receipt_button_text: 'Open Ledgerlane', receipt_link_url: `${appUrl}/app` } }, relationships: { store: { data: { type: 'stores', id: String(env.LEMONSQUEEZY_STORE_ID) } }, variant: { data: { type: 'variants', id: String(variant) } } } } }; const checkout = await externalJson('https://api.lemonsqueezy.com/v1/checkouts', { Authorization: `Bearer ${env.LEMONSQUEEZY_API_KEY}`, Accept: 'application/vnd.api+json', 'Content-Type': 'application/vnd.api+json' }, payload); return checkout.data?.attributes?.url || null; }
function verifyLemonSignature(raw, signature) { if (!env.LEMONSQUEEZY_WEBHOOK_SECRET || !signature) return false; const expected = createHmac('sha256', env.LEMONSQUEEZY_WEBHOOK_SECRET).update(raw).digest('hex'); return expected.length === signature.length && timingSafeEqual(Buffer.from(expected), Buffer.from(signature)); }
async function geminiAnswer(question, context) { if (!env.GEMINI_API_KEY) return null; const model = env.GEMINI_MODEL || 'gemini-2.5-flash'; const prompt = `You are Lane, a finance assurance assistant. Answer only from the supplied Ledgerlane workspace context. If the context is insufficient, say so plainly. Do not invent source documents, balances, or approvals. Be concise, useful, and professional.\n\nQuestion: ${question}\n\nWorkspace context:\n${context}`; const result = await externalJson(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(env.GEMINI_API_KEY)}`, {}, { contents: [{ role: 'user', parts: [{ text: prompt }] }], generationConfig: { temperature: 0.2, maxOutputTokens: 500 } }); return result.candidates?.[0]?.content?.parts?.map(part => part.text || '').join('').trim() || null; }
const buckets = new Map();
function rateLimit(req, res) { const forwarded = req.headers['x-forwarded-for']; const key = (typeof forwarded === 'string' ? forwarded.split(',')[0] : req.socket.remoteAddress || 'unknown').trim(); const entry = buckets.get(key) || { count: 0, reset: Date.now() + 60_000 }; if (Date.now() > entry.reset) { entry.count = 0; entry.reset = Date.now() + 60_000; } entry.count += 1; buckets.set(key, entry); if (entry.count > 120) { error(res, 429, 'Too many requests. Please try again shortly.'); return false; } return true; }
const mime = { '.html': 'text/html; charset=utf-8', '.css': 'text/css; charset=utf-8', '.js': 'application/javascript; charset=utf-8', '.xml': 'application/xml; charset=utf-8', '.txt': 'text/plain; charset=utf-8', '.svg': 'image/svg+xml', '.ico': 'image/x-icon' };
async function staticFile(req, res, pathname) { const requested = pathname === '/' ? 'landing.html' : pathname === '/app' ? 'index.html' : pathname.slice(1); const file = normalize(join(root, requested)); if (relative(root, file).startsWith('..')) return error(res, 403, 'Forbidden'); try { const info = await stat(file); if (!info.isFile()) throw new Error('Not a file'); const cache = extname(file) === '.html' ? 'no-cache' : 'public, max-age=604800, immutable'; res.writeHead(200, { ...securityHeaders, 'Content-Type': mime[extname(file)] || 'application/octet-stream', 'Cache-Control': cache }); createReadStream(file).pipe(res); } catch { error(res, 404, 'Not found'); } }

const server = createServer(async (req, res) => {
  const url = new URL(req.url, appUrl), path = url.pathname;
  try {
    if (!rateLimit(req, res) || !assertSameOrigin(req, res)) return;
    if (path === '/api/health' && req.method === 'GET') return json(res, 200, { status: 'ok', timestamp: now() });
    if (path === '/api/readiness' && req.method === 'GET') return json(res, 200, { status: 'ready', database: Boolean(one('SELECT 1 ok')), timestamp: now() });
    if (path === '/api/auth/demo' && req.method === 'POST') { if (!allowDemo) return error(res, 404, 'Not found'); const user = one('SELECT id FROM users WHERE email=?', 'leila@atlas.example'); setSession(res, user.id); return json(res, 200, { ok: true, redirect: '/app' }); }
    if (path === '/api/auth/signup' && req.method === 'POST') { const input = await jsonBody(req); const name = cleanText(input.name, 80), organization = cleanText(input.organization, 120), email = cleanText(input.email, 160).toLowerCase(), password = input.password || ''; if (!name || !organization || !emailPattern.test(email) || password.length < 12) return error(res, 400, 'Enter your name, organization, valid work email, and a password of at least 12 characters.'); if (one('SELECT id FROM users WHERE email=?', email)) return error(res, 409, 'An account with that email already exists.'); const orgId = id(), userId = id(), credential = hashPassword(password), timestamp = now(); run('INSERT INTO organizations VALUES (?, ?, ?, ?)', orgId, organization, 'starter', timestamp); run('INSERT INTO users VALUES (?, ?, ?, ?, ?, ?, ?, ?)', userId, orgId, email, name, 'owner', credential.salt, credential.hash, timestamp); run('INSERT INTO subscriptions VALUES (?, NULL, NULL, ?, ?, ?)', orgId, 'starter', 'active', timestamp); record(orgId, userId, 'created', 'organization', orgId); setSession(res, userId); return json(res, 201, { ok: true, redirect: '/app' }); }
    if (path === '/api/auth/login' && req.method === 'POST') { const input = await jsonBody(req), email = cleanText(input.email, 160).toLowerCase(), user = one('SELECT * FROM users WHERE email=?', email); if (!user || !verifyPassword(input.password || '', user.password_salt, user.password_hash)) return error(res, 401, 'Invalid email or password.'); setSession(res, user.id); return json(res, 200, { ok: true, redirect: '/app' }); }
    if (path === '/api/auth/logout' && req.method === 'POST') { const token = parseCookies(req.headers.cookie).ledgerlane_session; if (token) run('DELETE FROM sessions WHERE token_hash=?', hashToken(token)); clearSession(res); return json(res, 200, { ok: true }); }
    if (path === '/api/leads' && req.method === 'POST') { const input = await jsonBody(req), name = cleanText(input.name, 80), company = cleanText(input.company, 120), email = cleanText(input.email, 160).toLowerCase(), teamSize = cleanText(input.teamSize, 32), notes = cleanText(input.notes, 1000); if (!name || !company || !emailPattern.test(email) || !teamSize) return error(res, 400, 'Name, company, work email, and team size are required.'); if (!one('SELECT id FROM leads WHERE email=?', email)) run('INSERT INTO leads VALUES (?, ?, ?, ?, ?, ?, ?, ?)', id(), email, name, company, teamSize, notes, 'website', now()); return json(res, 201, { ok: true, message: 'Your briefing is confirmed. We will be in touch shortly.' }); }
    if (path === '/api/me' && req.method === 'GET') { const user = requireActor(req, res); if (user) return json(res, 200, { user }); return; }
    if (path === '/api/dashboard' && req.method === 'GET') { const user = requireActor(req, res); if (user) return json(res, 200, dashboard(user)); return; }
    if (path === '/api/intelligence/brief' && req.method === 'POST') { const user = requireActor(req, res); if (!user) return; const { question } = await jsonBody(req); const prompt = cleanText(question, 500); if (!prompt) return error(res, 400, 'Ask Lane a specific question about this close.'); const risks = all('SELECT title, description, amount_cents FROM exceptions WHERE org_id=? AND status=? ORDER BY amount_cents DESC LIMIT 3', user.org_id, 'open'); const workflows = all('SELECT title, status, progress FROM workflows WHERE org_id=? ORDER BY updated_at DESC LIMIT 3', user.org_id); const topRisk = risks[0], fallback = topRisk ? `Lane found ${risks.length} open close item${risks.length === 1 ? '' : 's'}. The highest-impact item is “${topRisk.title}” at ${money(topRisk.amount_cents)}: ${topRisk.description}. ${workflows.length ? `${workflows.filter(item => item.status === 'review').length} workflow${workflows.filter(item => item.status === 'review').length === 1 ? ' is' : 's are'} awaiting review.` : ''}` : 'This close has no open exceptions. All active workflow evidence is available in the close activity trail.'; const context = JSON.stringify({ risks: risks.map(item => ({ title: item.title, description: item.description, amount: money(item.amount_cents) })), workflows: workflows.map(item => ({ title: item.title, status: item.status, progress: item.progress })) }); let answer = fallback; try { answer = await geminiAnswer(prompt, context) || fallback; } catch (geminiError) { console.error(JSON.stringify({ level: 'warn', service: 'gemini', message: geminiError.message, at: now() })); } record(user.org_id, user.id, 'asked', 'intelligence_query', id(), { question: prompt.slice(0, 180) }); return json(res, 200, { answer, sources: [...risks.map(item => item.title), ...workflows.map(item => item.title)].slice(0, 4), model: env.GEMINI_API_KEY ? (env.GEMINI_MODEL || 'gemini-2.5-flash') : 'rules-based' }); }
    if (path === '/api/workflows' && req.method === 'GET') { const user = requireActor(req, res); if (user) return json(res, 200, { workflows: all('SELECT * FROM workflows WHERE org_id=? ORDER BY updated_at DESC', user.org_id) }); return; }
    if (path === '/api/workflows' && req.method === 'POST') { const user = requireActor(req, res, roleCanWrite); if (!user) return; const input = await jsonBody(req), types = { reconciliation: 'Reconcile an account', accrual: 'Prepare an accrual', evidence: 'Collect control evidence' }; if (!types[input.type]) return error(res, 400, 'Unsupported workflow type.'); const timestamp = now(), title = cleanText(input.title, 120) || types[input.type], workflow = { id: id(), org_id: user.org_id, type: input.type, title, status: 'draft', progress: 0, owner_id: user.id, due_date: typeof input.dueDate === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(input.dueDate) ? input.dueDate : null, created_at: timestamp, updated_at: timestamp }; run('INSERT INTO workflows VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', workflow.id, workflow.org_id, workflow.type, workflow.title, workflow.status, workflow.progress, workflow.owner_id, workflow.due_date, workflow.created_at, workflow.updated_at); record(user.org_id, user.id, 'created', 'workflow', workflow.id, { title: workflow.title }); return json(res, 201, { workflow }); }
    const workflowMatch = path.match(/^\/api\/workflows\/([a-f0-9]{32})$/); if (workflowMatch && req.method === 'PATCH') { const user = requireActor(req, res, roleCanWrite); if (!user) return; const existing = one('SELECT * FROM workflows WHERE id=? AND org_id=?', workflowMatch[1], user.org_id); if (!existing) return error(res, 404, 'Workflow not found.'); const input = await jsonBody(req), status = ['draft','active','review','complete'].includes(input.status) ? input.status : existing.status, progress = Number.isInteger(input.progress) && input.progress >= 0 && input.progress <= 100 ? input.progress : existing.progress; run('UPDATE workflows SET status=?, progress=?, updated_at=? WHERE id=?', status, progress, now(), existing.id); record(user.org_id, user.id, 'updated', 'workflow', existing.id, { status, progress }); return json(res, 200, { workflow: one('SELECT * FROM workflows WHERE id=?', existing.id) }); }
    if (path === '/api/exceptions' && req.method === 'GET') { const user = requireActor(req, res); if (user) return json(res, 200, { exceptions: all('SELECT * FROM exceptions WHERE org_id=? ORDER BY created_at DESC', user.org_id) }); return; }
    const exceptionMatch = path.match(/^\/api\/exceptions\/([a-f0-9]{32})\/resolve$/); if (exceptionMatch && req.method === 'POST') { const user = requireActor(req, res, roleCanWrite); if (!user) return; const item = one('SELECT * FROM exceptions WHERE id=? AND org_id=?', exceptionMatch[1], user.org_id); if (!item) return error(res, 404, 'Exception not found.'); if (item.status === 'resolved') return error(res, 409, 'This exception is already resolved.'); run('UPDATE exceptions SET status=?, resolved_at=? WHERE id=?', 'resolved', now(), item.id); record(user.org_id, user.id, 'resolved', 'exception', item.id, { title: item.title }); return json(res, 200, { ok: true }); }
    if (path === '/api/audit' && req.method === 'GET') { const user = requireActor(req, res, ['owner','admin','controller','auditor']); if (user) return json(res, 200, { events: all('SELECT * FROM audit_events WHERE org_id=? ORDER BY created_at DESC LIMIT 100', user.org_id) }); return; }
    if (path === '/api/billing' && req.method === 'GET') { const user = requireActor(req, res, ['owner','admin']); if (user) return json(res, 200, { subscription: one('SELECT * FROM subscriptions WHERE org_id=?', user.org_id), plans: [{ id: 'starter', price: 0, label: 'Starter' }, { id: 'growth', price: 499, label: 'Growth' }, { id: 'scale', price: 1499, label: 'Scale' }] }); return; }
    if (path === '/api/billing/checkout' && req.method === 'POST') { const user = requireActor(req, res, ['owner','admin']); if (!user) return; const { plan } = await jsonBody(req); if (!['growth','scale'].includes(plan)) return error(res, 400, 'Choose Growth or Scale.'); const checkoutUrl = await lemonCheckout(plan, user); if (!checkoutUrl) return error(res, 503, 'Lemon Squeezy billing is not configured for this environment.'); return json(res, 200, { checkoutUrl }); }
    if (path === '/api/webhooks/lemonsqueezy' && req.method === 'POST') { const raw = await readBody(req, 2_000_000); if (!verifyLemonSignature(raw, req.headers['x-signature'])) return error(res, 400, 'Invalid webhook signature.'); const event = JSON.parse(raw), attributes = event.data?.attributes || {}, custom = event.meta?.custom_data || {}, orgId = custom.org_id; const subscriptionEvents = new Set(['subscription_created','subscription_updated','subscription_cancelled','subscription_expired','subscription_resumed','subscription_paused','subscription_unpaused']); if (subscriptionEvents.has(event.meta?.event_name) && orgId) { const owner = one('SELECT id FROM users WHERE org_id=? ORDER BY created_at LIMIT 1', orgId); if (owner) { const status = attributes.status || (event.meta.event_name === 'subscription_cancelled' ? 'cancelled' : 'active'); run('UPDATE subscriptions SET provider_customer_id=?, provider_subscription_id=?, plan=?, status=?, updated_at=? WHERE org_id=?', String(attributes.customer_id || ''), String(event.data?.id || ''), custom.plan || 'growth', status, now(), orgId); record(orgId, owner.id, event.meta.event_name, 'subscription', String(event.data?.id || ''), { status }); } } return json(res, 200, { received: true }); }
    if (path.startsWith('/api/')) return error(res, 404, 'Unknown API route.');
    return staticFile(req, res, path);
  } catch (caught) { const status = Number.isInteger(caught.status) ? caught.status : 500; console.error(JSON.stringify({ level: 'error', method: req.method, path, message: caught.message, at: now() })); return error(res, status, status === 500 ? 'Something went wrong. Please try again.' : caught.message); }
});
const cleanup = setInterval(() => { run('DELETE FROM sessions WHERE expires_at<?', now()); if (buckets.size > 5000) buckets.clear(); }, 60 * 60 * 1000); cleanup.unref?.();
server.listen(port, () => console.log(`Ledgerlane is running at ${appUrl}`));
export { server };
